# Generated by Django 3.2.13 on 2023-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
